### ISSUE TITLE
Compile listview with arc throws GLib-GIO-CRITICAL

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/gintro#131] opened 2021-05-26 21:41 UTC
The already well known example )  
```nim
import gintro/[gtk4, gobject, gio]
import std/with

proc setup_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild(newLabel(""))
  
proc bind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  var 
    lb = listitem.getChild().Label
    strobj = cast[StringObject](listitem.getItem())
    txt = gtk4.getString(strobj)
  echo txt
  lb.text = txt

proc unbind_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  # There's nothing to do here. 
  # If you does something like setting a signal in bind_cb,
  # then disconnecting the signal is necessary in unbind_cb. 
  echo "unbind"

proc teardown_cb(factory: gtk4.SignalListItemFactory, listitem: gtk4.ListItem) =
  listitem.setChild (nil)
  # When the child of listitem is set to NULL, the reference to GtkLabel will be released and lb will be destroyed. 
  # Therefore, g_object_unref () for the GtkLabel object doesn't need in the user code. 

proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()

    sl = gtk4.newStringList("Nim", "Vala", "Rust", "Zig")
    ls = cast[ListModel](sl)
    ns = gtk4.newNoSelection(ls)
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
  
  scr.setChild lv

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    defaultSize = (600, 400)
    title = "Nim ListView"
    setChild scr
    show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  discard run(app)

main()
```

Compile with `nim c -r list_view.nim` then clicking on text items - all good   
Compile with `nim c -r --gc=arc  list_view.nim` then clicking on text - throws many `GLib-GIO-CRITICAL`

**Comment by StefanSalewski** [comment] 2021-05-27 05:45
Interesting.

The example from

https://github.com/StefanSalewski/gintro/issues/128#issuecomment-846857128

gave no issues with ARC for me.

Can you tell us what line of code you added/modified to get the issue. And when you compile with default refc GC and add GC_fullcollect() calls, do you get issues then too. Well I assume yes, I will investigate the issue soon. Problem for me is still that I do not know enough about all the listview stuff, so I am often not sure if it is a gintro bug or just misuse of GTK. I got a few issues in the past where people just did stupid things which would not really work for C as well...

**Comment by StefanSalewski** [comment] 2021-05-27 11:38
Well, that was your bug. You have rearranged so much that it took me some time to see the issue.

This works:

```nim
proc activate(app: gtk4.Application) =
  let
    window = newApplicationWindow(app)
    scr = newScrolledWindow()

    sl = cast[ListModel](gtk4.newStringList("Nim", "Vala", "Rust", "Zig"))
    #ls = cast[ListModel](sl) # newer do this, this generates a copy!!!
    ns = gtk4.newNoSelection(sl) # (ls)
    factory = gtk4.newSignalListItemFactory()
    lv = newListView(ns, factory)
  
  scr.setChild lv

  with factory:
    connect("setup", setup_cb)
    connect("bind", bind_cb)
    connect("unbind", unbind_cb)
    connect("teardown", teardown_cb)

  with window:
    defaultSize = (600, 400)
    title = "Nim ListView"
    setChild scr
    show
```

The issue is your cast

```
let ls = cast[ListModel](sl)
```

That is similar to
```
let b = newButton()
let b2 = b
```

Of course we never do that, not in plain C, and not in Nim. I am not sure what exactly is going on in your wrong code, I would have to see what that newStringList() return type exactly is. But it is clear that it is wrong. We can do cast() a variable when really necessary, but only cast the type of an existing variable, not generate copies that way.

For our nil issue with the or types I have generated a issue in Nim issue tracker.

**Comment by gavr123456789** [comment] 2021-05-27 15:56
Ohh, yea, didnt know cast makes copy.

**Comment by StefanSalewski** [comment] 2021-05-28 07:25
I have still no idea what happens in detail. Just doing a cast copy of a ref should not be a problem when we do not use both variables. And in a small test program with destructors and compiled wit ARC it is indeed fine.

Unfortunately I do not understand the listview stuff well.

**Comment by StefanSalewski** [comment] 2021-06-01 07:38
Should be fixed now. You can try with

```
nimble uninstall gintro
nimble install gintro@#head
```

**Closed by StefanSalewski** 2021-06-01 07:38 UTC
