### ISSUE TITLE
CssProvider

### ISSUE THREAD

**Issue by pekim** [StefanSalewski/gintro#2] opened 2017-07-17 18:00 UTC
I'm having a bit of a problem adding a CssProvider.

This is what I've tried.
```nim
  let window = newApplicationWindow(app)
  let css = "#test { background-color: red; }"

  let cssProvider = newCssProvider()
  assert(cssProvider.loadFromData(cstring(css), int64(len(css))))
  window.getStyleContext().addProvider(cast[StyleProvider](cssProvider.impl), int(STYLE_PROVIDER_PRIORITY_USER))
```
It results in an gtk error message.
```
(mixlac:20468): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_PROVIDER (provider)' failed
```

The cast from CssProvider to StyleProvider is possibly not the right thing to do, but I can't figure how it should be.

**Comment by StefanSalewski** [comment] 2017-07-17 20:51
You are doing heavy testing already, thanks.

Indeed adding a CssProvider is fully untested still, I can remember having some problems in Ruby some years ago with it. Will investigate that soon, but may take a few days...

**Comment by StefanSalewski** [comment] 2017-07-18 06:06
The problem is the casting between CssProvider and StyleProvider.

I tried this C example: https://stackoverflow.com/questions/30791670/how-to-style-a-gtklabel-with-css

This Nim code is working for me:

```nim
import gintro/[gtk, glib]
import gintro/gio except Application, newApplication

proc activate(app: Application) =
  let window = newApplicationWindow(app)
  let label = newLabel("Text")
  var cssProvider: CssProvider = newCssProvider()
  var data: string = "* {color: green;}"
  assert cssProvider.loadFromData(uint8Array(data.cstring), -1)
  let styleContext: StyleContext = window.getStyleContext
  assert styleContext != nil
  gtk_style_context_add_provider(cast[ptr StyleContext00](styleContext.impl), cast[ptr StyleProvider00](cssProvider.impl), STYLE_PROVIDER_PRIORITY_USER.uint32)
  window.add(label)
  showAll(window)

proc main =
  let app = newApplication("org.gtk.example")
  connect(app, "activate", activate)
  discard run(app)

main()
```

Here I used the low level gtk_style_context_add_provider(). Of course that can not be the final solution, I have to investigate how CssProvider/StyleProvider conversion can be done with gobject-introspection. That Nim program makes all the text green, as I used the * unfortunately.

**Comment by StefanSalewski** [comment] 2017-07-18 12:54
The problem are the gobject interfaces. In Nim we want to call our procs without casts. So for all procs with parameters of type interface, I have to add a proc variant which accepts argument types which provide that interface. For example

```
proc addProvider*(self: StyleContext; provider: StyleProvider | CSSProvider; priority: int) =
  gtk_style_context_add_provider(cast[ptr StyleContext00](self.impl), cast[ptr StyleProvider00](provider.impl), uint32(priority))
```

Then this works:

```
addProvider(styleContext, cssProvider, STYLE_PROVIDER_PRIORITY_USER.int)
```

I hope my understanding of the gobject interfaces is correct, I think that a proc which accepts an interface data type, also accepts any gobject which defines that interface.

Unfortunately finding all gobject datatypes which provides interfaces is some additional work for the generator program. And it additional makes sorting of data types and procs more difficult,as all proc parameter data types has to be defined before they are used in a proc call. 

So it may take some time to get this working properly.

**Comment by pekim** [comment] 2017-07-18 19:13
Your example workaround works for me. Thank you.

> In Nim we want to call our procs without casts.

Yes it would be nice to keep the api calls free of casts.

And also free of conversions. So that
```nim
cssProvider.loadFromData(uint8Array(data.cstring), -1)
```
would be
```nim
cssProvider.loadFromData(data)
```

**Comment by StefanSalewski** [comment] 2017-07-21 17:07
I have just uploaded the latest gen.nim generator with support for GTK's interfaces. Additional GErrors are now mapped to Nim's exceptions. Readme contains an example for that, at the bottom.

Closing, please reopen when problems occur.

**Closed by StefanSalewski** 2017-07-21 17:07 UTC
