### ISSUE TITLE
Installation on Debian 10 fails with obscure SIGSEGV

### ISSUE THREAD

**Issue by a-mr** [StefanSalewski/gintro#151] opened 2021-07-12 15:25 UTC
Attempt to install on Debian stable (10) failed. I tried to install it a few months ago with the same result. Please advice how to proceed.

The log:
```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
...
$ nimble -v
nimble v0.13.1 compiled at 2021-07-12 15:07:02
$ nimble install --verbose gintro
nimble install --verbose gintro
    Reading official package list
Downloading https://github.com/stefansalewski/gintro using git
    Cloning latest tagged version: v0.9.3
 Attempting to execute hook installBefore in /tmp/nimble_16312/githubcom_stefansalewskigintro/gintro.nimble
preparing gintro
--2021-07-12 18:20:01--  https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/gobject.nim
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 108015 (105K) [text/plain]
Saving to: ‘gobject.nim’

gobject.nim         100%[===================>] 105.48K  --.-KB/s    in 0.06s   

2021-07-12 18:20:02 (1.86 MB/s) - ‘gobject.nim’ saved [108015/108015]

--2021-07-12 18:20:02--  https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/glib.nim
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 256798 (251K) [text/plain]
Saving to: ‘glib.nim’

glib.nim            100%[===================>] 250.78K  --.-KB/s    in 0.06s   

2021-07-12 18:20:02 (3.94 MB/s) - ‘glib.nim’ saved [256798/256798]

--2021-07-12 18:20:02--  https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/gir.nim
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33340 (33K) [text/plain]
Saving to: ‘gir.nim’

gir.nim             100%[===================>]  32.56K  --.-KB/s    in 0.006s  

2021-07-12 18:20:02 (5.02 MB/s) - ‘gir.nim’ saved [33340/33340]

Hint: used config file '/home/amakarov/activity-shared/nim-stable/config/nim.cfg' [Conf]
Hint: used config file '/home/amakarov/activity-shared/nim-stable/config/config.nims' [Conf]
....................
/tmp/gintrosalewski/glib.nim(2914, 3) Hint: 'G_NORMALIZE_NFKC' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(3040, 3) Hint: 'G_IO_FLAGS_GET_MASK' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(31, 3) Hint: 'GTK_DOC_IGNORE' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(34, 3) Hint: 'INC_STDLIB' is declared but not used [XDeclaredButNotUsed]                                                           
/tmp/gintrosalewski/glib.nim(1806, 3) Hint: 'G_TRAVERSE_MASK' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(26, 3) Hint: 'MINGW_H' is declared but not used [XDeclaredButNotUsed]                                                              
/tmp/gintrosalewski/glib.nim(1807, 3) Hint: 'G_TRAVERSE_LEAFS' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(23, 3) Hint: 'GLIB_COMPILATION' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(2912, 3) Hint: 'G_NORMALIZE_NFC' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(1808, 3) Hint: 'G_TRAVERSE_NON_LEAFS' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(2911, 3) Hint: 'G_NORMALIZE_NFD' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(22, 3) Hint: 'GLIB_H_INSIDE' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(4652, 3) Hint: 'G_REGEX_MATCH_PARTIAL_SOFT' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(27, 3) Hint: 'STDLIB_H' is declared but not used [XDeclaredButNotUsed]                                                             
/tmp/gintrosalewski/glib.nim(2913, 3) Hint: 'G_NORMALIZE_NFKD' is declared but not used [XDeclaredButNotUsed]
/tmp/gintrosalewski/glib.nim(29, 3) Hint: 'MSC_VER' is declared but not used [XDeclaredButNotUsed]                                                              
.
/tmp/gintrosalewski/gobject.nim(658, 3) Hint: 'G_PARAM_READWRITE' is declared but not used [XDeclaredButNotUsed]
.........
/tmp/gintrosalewski/gen.nim(209, 6) Hint: 'endsWith' is declared but not used [XDeclaredButNotUsed]                                                             
/tmp/gintrosalewski/gen.nim(65, 10) Hint: 'isTypeInfo' is declared but not used [XDeclaredButNotUsed]                                                           
/tmp/gintrosalewski/gen.nim(261, 6) Hint: 'renumber' is declared but not used [XDeclaredButNotUsed]                                                             
Hint:  [Link]
Hint: 65450 lines; 1.138s; 117.824MiB peakmem; Debug build; proj: /tmp/gintrosalewski/gen.nim; out: /tmp/gintrosalewski/gen [SuccessX]
First we try generating bindings for GTK4, this may fail when GTK4 is not properly installed
on your computer. But don't worry, you can still use GTK3
Can't load gtk4 library!
Failed to load Gtk
Typelib file for namespace 'Gtk', version '4.0' not found
Maybe for your OS you have to install additional GTK related packages?
We continue with the remaining packages...
Failed to load Gdk
Typelib file for namespace 'Gdk', version '4.0' not found
Maybe for your OS you have to install additional GTK related packages?
We continue with the remaining packages...
Failed to load GdkX11
Typelib file for namespace 'GdkX11', version '4.0' not found
Maybe for your OS you have to install additional GTK related packages?
We continue with the remaining packages...
Failed to load Gsk
Typelib file for namespace 'Gsk' (any version) not found
Maybe for your OS you have to install additional GTK related packages?
We continue with the remaining packages...
graphene................: Remaining delayed methods: 0 (Fine!)
Traceback (most recent call last)
/tmp/gintrosalewski/gen.nim(4261) gen
/tmp/gintrosalewski/gen.nim(4192) launch
/tmp/gintrosalewski/gen.nim(3768) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
stack trace: (most recent call last)
/tmp/nimblecache-3558437777/nimscriptapi_756804212.nim(199, 29)
/tmp/nimble_16312/githubcom_stefansalewskigintro/gintro.nimble(77, 7) installBefore
/tmp/nimble_16312/githubcom_stefansalewskigintro/gintro.nimble(64, 7) prep
/home/amakarov/activity-shared/nim-stable/lib/system/nimscript.nim(260, 7) exec
/home/amakarov/activity-shared/nim-stable/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: /tmp/gintrosalewski/gen 1 [OSError]
     Error: Exception raised during nimble script execution
```

**Comment by StefanSalewski** [comment] 2021-07-12 19:25
Thanks for reporting.

That is an interesting and strange bug, which has never been seen before. The error position gen.nim(3768) is really strange.

Are you installing on a tiny device like a RasberyPi so that it may just be a out of mem condition?

Are you using a 32 bit Linux or maybe a none x86 system like ARM or MIPS or RISCV.

I assume that you are very new to GTK, as you have never tried gintro in the last 6 years. So I would advice you to just use one of the 20 other Nim GUI toolkits. I have listed their names in the GTK4 book at the beginning, see  http://ssalewski.de/gtkprogramming.html. Araq and the other Nim core devs seems to advertise Fidget most currently. Learning GTK for beginners is a large task unfortunately, the gintro bindings are still not that good as the Rust bindings, and number of gintro users is small.

For you discovered bug, I will certainly try to discover the reason, but I have no good idea currently.

**Comment by a-mr** [comment] 2021-07-13 19:03
@StefanSalewski ,

No, it's just a normal x86_64 PC with 16 GB of RAM.

> Araq and the other Nim core devs seems to advertise Fidget most currently

Thank you very much for advice, I will take a closer look at that library also.

**Comment by StefanSalewski** [comment] 2021-08-25 07:19
We will close this issue now as we can currently not reproduce it and have now idea for the reason.

**Closed by StefanSalewski** 2021-08-25 07:19 UTC
